### ISSUE TITLE
multiCheckbox questions do not render in Preview

### ISSUE THREAD

**Issue by gracepotma** [openmrs/openmrs-esm-form-builder#73]
To reproduce:

- Use this JSON file: https://docs.google.com/document/d/1qnYYCQdkZcql1wOtttZxSdlY_VKYTEK2xOSgbq11Q3Q/edit 
- Apply this in the Form Builder
- Try changing the last Urine section question from Radio to multiCheckbox (e.g. Crystals type in urine sediment by light microscopy test) - this is a good example of a question that could have multiple true answers. 
- Notice the question **no longer shows up** in the preview mode.

**Comment by denniskigen** [comment]
`multiCheckbox` questions don't render because that `rendering` type is not known to the form engine. It only knows how to render `checkbox` fields. This is a two-pronged problem because:

- Currently, the forms built using the form builder get rendered in O3 via the Angular form engine. The Angular form engine knows how to render `multiCheckbox` fields whereas the Form Builder does not. This means that if you have a `multiCheckbox` field in your schema, it won't render in the Form Builder preview, but will render fine in the reference application using the Angular form engine.

- In lieu of the above, whatever solution we adopt would have to take into account the fact that forms built using the Angular form engine use `multiCheckbox` whereas those built using the React form engine use `checkbox`, and that these fields are expected to work in the same way using both form engines. We shouldn't require users to amend their forms to account for this mismatch.
